### Get All 


GET http://localhost:3000/reports/



### create

POST http://localhost:3000/reports
Content-Type: application/json

{
    "make" : "pmw",
    "model" : "116i",
    "year": 2019,
    "price" : 600000
}